### PR TITLE
Common js integration

### PR DESCRIPTION
**Pull request by t128**

### CODE REVIEW

**Comment by pleasetrythisathome** [comment]
excellent thanks! what environments have you tested this under?

**Comment by t128** [comment]
> tested

what's that? ;)
maybe i pressed the "create pull request" button to early ;)

**Comment by t128** [comment]
yeah, it works with browserify, but not node.

**Comment by pleasetrythisathome** [comment]
will consider what to do in the node case. having no window object defined should cause the interpolator returns to constantly return the start value, for server rendering situations

**Comment by t128** [comment]
*update*, so i'm using it now for render my widgets also on the server

**Comment by pleasetrythisathome** [comment]
perfect.

**Comment by t128** [comment]
ok :(

**Comment by pleasetrythisathome** [comment]
sad face?

**Comment by geekytime** [comment]
Was this intended to be merged instead of closed?

**Comment by t128** [comment]
seams so :(

anyway, i wanted to fork this repo, when i need it again

**Comment by pleasetrythisathome** [comment]
woops wrong button there. merged now

**Comment by geekytime** [comment]
Ha ha. I wondered about that. :smiley_cat:

**Pull request merged**
